tests_dir: './tests'
client_config:
  region_name: 'ap-southeast-1'
identities:
  admin:
    account_id: 'xxx'
    aws_access_key_id: 'xxx'
    aws_secret_access_key: 'xxx'
  anonymous:
    account_id: '65a011a29cdf8ec533ec3d1ccaae921c'
global_variables:
  group_all_users_url: 'http://acs.amazonaws.com/groups/global/AllUsers'
  group_authenticated_users_url: 'http://acs.amazonaws.com/groups/global/AuthenticatedUsers'