tests_dir: './suites'
#load_xmind_suites: false
#load_yaml_suites: true
load_xmind_suites: true
load_yaml_suites: false
client_config:
  region_name: 'ap-southeast-1'
identities:
  admin:
    account_id: 'xxx'
    aws_access_key_id: 'xxx'
    aws_secret_access_key: 'xxx'
  anonymous:
    account_id: '65a011a29cdf8ec533ec3d1ccaae921c'
global_variables:
  group_all_users_url: 'http://acs.amazonaws.com/groups/global/AllUsers'
  group_authenticated_users_url: 'http://acs.amazonaws.com/groups/global/AuthenticatedUsers'
exporters:
  xmind:
    file_path: .wd/xmind_exports/aws_tests.xmind
    include_fields: [ 'parameters', 'assertion', 'response', 'errorInfo' ]
hide_enabled: true
suite_filters:
  includes:
    - '.*AbortMultipartUpload.*'
  #    - '.*Ownership-ObjectWriter.*'
  excludes:
#    - '.*'